name: Test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  rspec:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Setup
        run: bin/setup

      - name: Run tests
        run: bin/rspec


  test-xlsx2yaml:
    name: Run xlsx2yaml
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Setup
        run: bin/setup

      - name: Run command
        run: make test-xlsx2yaml


  test-xlsx2db:
    name: Run xlsx2db
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Setup
        run: bin/setup

      - name: Run command
        run: make test-xlsx2db


  test-db2yaml:
    name: Run db2yaml
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Setup
        run: bin/setup

      - name: Run command
        run: make test-db2yaml
